# Generated by Django 5.2.4 on 2025-07-25 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComposicionConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField()),
                ('motivo_consulta', models.TextField(blank=True, null=True)),
                ('costo_consulta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_cancelado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.CharField(blank=True, max_length=50, null=True)),
                ('raza', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tratamiento', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('via_administracion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('veterinario', 'Veterinario'), ('recepcionista', 'Recepcionista'), ('cliente', 'Cliente')], max_length=20)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dosis_recomendada', models.CharField(blank=True, max_length=50, null=True)),
                ('edad_recomendada', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('clasificacion_cie', models.CharField(blank=True, max_length=10, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('composicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clinica.composicionconsulta')),
            ],
        ),
        migrations.AddField(
            model_name='composicionconsulta',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clinica.mascota'),
        ),
        migrations.CreateModel(
            name='ObservacionSintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('proporcionado_por', models.CharField(choices=[('cliente', 'Cliente'), ('chatbot', 'Chatbot'), ('veterinario', 'Veterinario')], max_length=20)),
                ('severidad_aparente', models.CharField(choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('grave', 'Grave')], max_length=20)),
                ('composicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clinica.composicionconsulta')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('contenido', models.TextField()),
                ('composicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clinica.composicionconsulta')),
            ],
        ),
        migrations.CreateModel(
            name='AccionTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_cancelado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('composicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clinica.composicionconsulta')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clinica.tratamiento')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='gestion_clinica.usuario'),
        ),
        migrations.CreateModel(
            name='LogAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=50)),
                ('fecha_acceso', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clinica.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='composicionconsulta',
            name='veterinario',
            field=models.ForeignKey(limit_choices_to={'rol': 'veterinario'}, on_delete=django.db.models.deletion.CASCADE, to='gestion_clinica.usuario'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateTimeField()),
                ('estado_cita', models.CharField(choices=[('pendiente', 'Pendiente'), ('asistida', 'Asistida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clinica.mascota')),
                ('veterinario', models.ForeignKey(limit_choices_to={'rol': 'veterinario'}, on_delete=django.db.models.deletion.CASCADE, to='gestion_clinica.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas_ingresados', models.TextField()),
                ('severidad_estimada', models.CharField(choices=[('no urgente', 'No Urgente'), ('moderado', 'Moderado'), ('crítico', 'Crítico')], max_length=20)),
                ('respuesta', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clinica.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MascotaVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField()),
                ('lote_vacuna', models.CharField(blank=True, max_length=50, null=True)),
                ('proxima_dosis', models.DateField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clinica.mascota')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clinica.vacuna')),
            ],
            options={
                'unique_together': {('mascota', 'vacuna', 'fecha_aplicacion')},
            },
        ),
    ]
