# Generated by Django 5.2.4 on 2025-07-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='acciontratamiento',
            table='accion_tratamiento',
        ),
        migrations.AlterModelTable(
            name='chatbotconsulta',
            table='chatbot_consulta',
        ),
        migrations.AlterModelTable(
            name='cita',
            table='cita',
        ),
        migrations.AlterModelTable(
            name='composicionconsulta',
            table='composicion_consulta',
        ),
        migrations.AlterModelTable(
            name='evaluaciondiagnostico',
            table='evaluacion_diagnostico',
        ),
        migrations.AlterModelTable(
            name='logacceso',
            table='log_acceso',
        ),
        migrations.AlterModelTable(
            name='mascota',
            table='mascota',
        ),
        migrations.AlterModelTable(
            name='mascotavacuna',
            table='mascota_vacuna',
        ),
        migrations.AlterModelTable(
            name='observacionsintoma',
            table='observacion_sintoma',
        ),
        migrations.AlterModelTable(
            name='receta',
            table='receta',
        ),
        migrations.AlterModelTable(
            name='tratamiento',
            table='tratamiento',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
        migrations.AlterModelTable(
            name='vacuna',
            table='vacuna',
        ),
    ]
